"""Static configuration: taxonomy, statement types, section patterns."""
from __future__ import annotations

XBRL_TAXONOMY: dict[str, str] = {
    # Income statement
    "Revenues": "revenue",
    "RevenueFromContractWithCustomerExcludingAssessedTax": "revenue",
    "SalesRevenueNet": "revenue",
    "CostOfGoodsAndServicesSold": "cost_of_revenue",
    "CostOfRevenue": "cost_of_revenue",
    "GrossProfit": "gross_profit",
    "ResearchAndDevelopmentExpense": "research_and_development",
    "SellingGeneralAndAdministrativeExpense": "selling_general_admin",
    "OperatingIncomeLoss": "operating_income",
    "InterestExpense": "interest_expense",
    "IncomeTaxExpenseBenefit": "income_tax",
    "NetIncomeLoss": "net_income",
    "EarningsPerShareBasic": "eps_basic",
    "EarningsPerShareDiluted": "eps_diluted",
    # Balance sheet
    "Assets": "total_assets",
    "AssetsCurrent": "current_assets",
    "CashAndCashEquivalentsAtCarryingValue": "cash_and_equivalents",
    "ShortTermInvestments": "short_term_investments",
    "AccountsReceivableNetCurrent": "accounts_receivable",
    "InventoryNet": "inventory",
    "Liabilities": "total_liabilities",
    "LiabilitiesCurrent": "current_liabilities",
    "LongTermDebtNoncurrent": "long_term_debt",
    "StockholdersEquity": "stockholders_equity",
    "RetainedEarningsAccumulatedDeficit": "retained_earnings",
    # Cash flow
    "NetCashProvidedByUsedInOperatingActivities": "operating_cash_flow",
    "NetCashProvidedByUsedInInvestingActivities": "investing_cash_flow",
    "NetCashProvidedByUsedInFinancingActivities": "financing_cash_flow",
    "PaymentsToAcquirePropertyPlantAndEquipment": "capex",
    "PaymentsOfDividends": "dividends_paid",
    "PaymentsForRepurchaseOfCommonStock": "share_buybacks",
}

STATEMENT_TYPES: dict[str, str] = {
    "revenue": "income",
    "cost_of_revenue": "income",
    "gross_profit": "income",
    "research_and_development": "income",
    "selling_general_admin": "income",
    "operating_income": "income",
    "interest_expense": "income",
    "income_tax": "income",
    "net_income": "income",
    "eps_basic": "income",
    "eps_diluted": "income",
    "total_assets": "balance",
    "current_assets": "balance",
    "cash_and_equivalents": "balance",
    "short_term_investments": "balance",
    "accounts_receivable": "balance",
    "inventory": "balance",
    "total_liabilities": "balance",
    "current_liabilities": "balance",
    "long_term_debt": "balance",
    "stockholders_equity": "balance",
    "retained_earnings": "balance",
    "operating_cash_flow": "cashflow",
    "investing_cash_flow": "cashflow",
    "financing_cash_flow": "cashflow",
    "capex": "cashflow",
    "dividends_paid": "cashflow",
    "share_buybacks": "cashflow",
}

NARRATIVE_SECTIONS: set[str] = {
    "ITEM 1. BUSINESS",
    "ITEM 1A. RISK FACTORS",
    "ITEM 7. MD&A",
    "ITEM 7A. QUANTITATIVE AND QUALITATIVE DISCLOSURES",
    "ITEM 2. MD&A (10-Q)",
}

SECTION_PATTERNS: list[tuple[str, str]] = [
    (r"(?i)ITEM\s+1\.?\s*[-–—.]?\s*BUSINESS", "ITEM 1. BUSINESS"),
    (r"(?i)ITEM\s+1A\.?\s*[-–—.]?\s*RISK\s+FACTORS", "ITEM 1A. RISK FACTORS"),
    (r"(?i)ITEM\s+1B\.?\s*[-–—.]?\s*UNRESOLVED\s+STAFF", "ITEM 1B. UNRESOLVED STAFF COMMENTS"),
    (r"(?i)ITEM\s+2\.?\s*[-–—.]?\s*PROPERTIES", "ITEM 2. PROPERTIES"),
    (r"(?i)ITEM\s+3\.?\s*[-–—.]?\s*LEGAL\s+PROCEEDINGS", "ITEM 3. LEGAL PROCEEDINGS"),
    (r"(?i)ITEM\s+5\.?\s*[-–—.]?\s*MARKET", "ITEM 5. MARKET FOR REGISTRANT'S COMMON EQUITY"),
    (r"(?i)ITEM\s+6\.?\s*[-–—.]?\s*(?:SELECTED|RESERVED)", "ITEM 6. RESERVED"),
    (r"(?i)ITEM\s+7\.?\s*[-–—.]?\s*MANAGEMENT", "ITEM 7. MD&A"),
    (r"(?i)ITEM\s+7A\.?\s*[-–—.]?\s*QUANTITATIVE", "ITEM 7A. QUANTITATIVE AND QUALITATIVE DISCLOSURES"),
    (r"(?i)ITEM\s+8\.?\s*[-–—.]?\s*FINANCIAL\s+STATEMENTS", "ITEM 8. FINANCIAL STATEMENTS"),
    (r"(?i)ITEM\s+9\.?\s*[-–—.]?\s*CHANGES\s+IN", "ITEM 9. CHANGES IN AND DISAGREEMENTS"),
    (r"(?i)ITEM\s+9A\.?\s*[-–—.]?\s*CONTROLS", "ITEM 9A. CONTROLS AND PROCEDURES"),
    (r"(?i)PART\s+I.*FINANCIAL\s+INFORMATION", "PART I. FINANCIAL INFORMATION"),
    (r"(?i)PART\s+II.*OTHER\s+INFORMATION", "PART II. OTHER INFORMATION"),
    (r"(?i)ITEM\s+1\.?\s*[-–—.]?\s*FINANCIAL\s+STATEMENTS", "ITEM 1. FINANCIAL STATEMENTS (10-Q)"),
    (r"(?i)ITEM\s+2\.?\s*[-–—.]?\s*MANAGEMENT.*DISCUSSION", "ITEM 2. MD&A (10-Q)"),
    (r"(?i)ITEM\s+3\.?\s*[-–—.]?\s*QUANTITATIVE", "ITEM 3. QUANTITATIVE DISCLOSURES (10-Q)"),
]
